#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    if command -v plymouth-set-default-theme >/dev/null 2>&1; then
        plymouth-set-default-theme tobixu || true
        update-initramfs -u || true
    fi
fi
exit 0
