#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    if btrfs subvolume list / >/dev/null 2>&1 \
       && ! snapper -c root list >/dev/null 2>&1; then
        snapper -c root create-config / || true
    fi
fi
exit 0
